"""add first name - last name - deleted index to user

Revision ID: 72a296bd7c4a
Revises: d706ca5431d5
Create Date: 2023-06-26 22:28:03.525041

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '72a296bd7c4a'
down_revision = 'd706ca5431d5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # text_pattern_ops is used to index case-sensitive text fields for pattern matching

    op.create_index(op.f('idx_user_first_name_last_name_deleted'),
                    'user',
                    ['first_name', 'last_name', 'deleted'],
                    unique=False,
                    postgresql_ops={'first_name': 'text_pattern_ops', 'last_name': 'text_pattern_ops'},
                    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_user_first_name_last_name_deleted', table_name='user')
    # ### end Alembic commands ###
