"""create replicator role

Revision ID: df4a0ebacc4a
Revises: 72a296bd7c4a
Create Date: 2023-07-09 12:16:53.243981

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'df4a0ebacc4a'
down_revision = '72a296bd7c4a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("CREATE ROLE replicator WITH LOGIN replication PASSWORD 'replicator';")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("DROP ROLE replicator;")
    # ### end Alembic commands ###
