version: "3.9"

volumes:
    postgres_data_0: {}
    postgres_data_1: {}
    postgres_data_2: {}
    postgres_data_tmp: {}
    prometheus_data: {}
    grafana_data: {}
    
networks:
  default:
    name: social-network-default
      external: true

services:
  db_0:
    image: postgres:15
    container_name: social-network-db_0
    volumes:
      - postgres_data_0:/var/lib/postgresql/data
      - ./postgres_config/postgresql.db0.conf:/etc/postgresql.conf
      - ./postgres_config/pg_hba.conf:/etc/pg_hba.conf
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=social_network_admin
      - POSTGRES_PASSWORD=social_network_password
      - POSTGRES_DB=social_network_db
      - POSTGRES_HOST_AUTH_METHOD=scram-sha-256
      - POSTGRES_CONFIG_FILE=/etc/postgresql.conf
      - POSTGRES_HBA_FILE=/etc/pg_hba.conf
    restart: unless-stopped
  
  # db_1:
  #   image: postgres:15
  #   container_name: social-network-db_1
  #   volumes:
  #     - postgres_data_1:/var/lib/postgresql/data
  #     - ./postgres_config/postgresql.db1.conf:/etc/postgresql.conf
  #     - ./postgres_config/pg_hba.conf:/etc/pg_hba.conf
  #     - ./postgres_config/standby.signal:/var/lib/postgresql/data/standby.signal
  #   ports:
  #     - "15432:5432"
  #   environment:
  #     - POSTGRES_USER=social_network_admin
  #     - POSTGRES_PASSWORD=social_network_password
  #     - POSTGRES_DB=social_network_db
  #     - POSTGRES_HOST_AUTH_METHOD=scram-sha-256
  #     - POSTGRES_CONFIG_FILE=/etc/postgresql.conf
  #     - POSTGRES_HBA_FILE=/etc/pg_hba.conf
  #   restart: unless-stopped

  # db_2:
  #   image: postgres:15
  #   container_name: social-network-db_2
  #   volumes:
  #     - postgres_data_2:/var/lib/postgresql/data
  #     - ./postgres_config/postgresql.db2.conf:/etc/postgresql.conf
  #     - ./postgres_config/pg_hba.conf:/etc/pg_hba.conf
  #     - ./postgres_config/standby.signal:/var/lib/postgresql/data/standby.signal
  #   ports:
  #     - "25432:5432"
  #   environment:
  #     - POSTGRES_USER=social_network_admin
  #     - POSTGRES_PASSWORD=social_network_password
  #     - POSTGRES_DB=social_network_db
  #     - POSTGRES_HOST_AUTH_METHOD=scram-sha-256
  #     - POSTGRES_CONFIG_FILE=/etc/postgresql.conf
  #     - POSTGRES_HBA_FILE=/etc/pg_hba.conf
  #   restart: unless-stopped

  backend:
    container_name: social-network-backend
    build:
      context: .
      dockerfile: ./Dockerfile
    volumes:
      - .:/code
    ports:
      - "8085:8085"
    depends_on:
      - db_0
      # - db_1
      # - db_2
    env_file:
      - .env.local
    environment:
      POSTGRES_HOST_AUTH_METHOD: scram-sha-256
    restart: unless-stopped

  # postgres_exporter:
  #   image: quay.io/prometheuscommunity/postgres-exporter
  #   container_name: social-network-postgres-exporter
  #   # command:
  #   #   - '--collector.stat_statements'
  #   ports:
  #     - "9187:9187"
  #   depends_on:
  #     - db_0
  #   environment:
  #     DATA_SOURCE_NAME: "postgresql://social_network_admin:social_network_password@db:5432/social_network_db?sslmode=disable"
  #   restart: always

  # prometheus:
  #   image: prom/prometheus
  #   container_name: social-network-prometheus
  #   volumes:
  #     - ./prometheus:/etc/prometheus
  #     - prometheus_data:/prometheus
  #   command:
  #     - '--config.file=/etc/prometheus/prometheus.yml'
  #     - '--storage.tsdb.path=/prometheus'
  #     - '--web.console.libraries=/usr/share/prometheus/console_libraries'
  #     - '--web.console.templates=/usr/share/prometheus/consoles'
  #   ports:
  #     - "9090:9090"
  #   depends_on:
  #     - postgres_exporter
  #   restart: unless-stopped


  # grafana:
  #   image: grafana/grafana
  #   container_name: social-network-grafana
  #   ports:
  #     - "3000:3000"
  #   depends_on:
  #     - prometheus
  #   volumes:
  #     - ./grafana/datasources:/etc/grafana/provisioning/datasources
  #     - ./grafana/dashboards:/etc/grafana/provisioning/dashboards
  #     - ./grafana/grafana.ini:/etc/grafana/grafana.ini
  #     - grafana_data:/var/lib/grafana
  #   # environment:
  #   #   - GF_AUTH_ANONYMOUS_ENABLED=true
  #   #   - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
  #   #   - GF_AUTH_DISABLE_LOGIN_FORM=true
  #   restart: unless-stopped
