version: "3.9"

services:
  db:
    image: postgres:11
    # container_name: social-network-postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=social_network_admin
      - POSTGRES_PASSWORD=social_network_password
      - POSTGRES_DB=social_network_db

  backend:
    # container_name: social-network-backend
    build:
      context: .
      dockerfile: ./Dockerfile
    volumes:
      - .:/code
    ports:
      - "8085:8085"
    depends_on:
      - db
    env_file:
      - .env.local
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust

networks:
  default:
    name: social-network-default
    external: true